[build]
  command = "npx pnpm run netlify-build"
  publish = "app/dist"

[[plugins]]
  package = "/netlify-plugins/pnpm-preinstaller"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
