name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 8.10.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm build-gh-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: app/dist 
