name: Typecheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  typecheck:
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Generate declarations
      run: pnpm run -r build-declaration
    - name: Typecheck
      run: pnpm run -r typecheck
